name: sensei
version: 0.7.0
synopsis: Automatically run Hspec tests on file modifications
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: hspec/sensei
category: Development

data-files: startup.ghci

language: GHC2021
default-extensions:
  - DuplicateRecordFields
  - LambdaCase
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards
  - ViewPatterns

other-extensions:
  - NoFieldSelectors

dependencies:
  - base >= 4.11 && < 5
  - process
  - fsnotify == 0.4.*
  - time
  - wai
  - warp
  - http-types
  - stm
  - text
  - network
  - ansi-terminal
  - directory
  - http-client >= 0.5.0
  - bytestring
  - filepath
  - unix
  - async
  - containers
  - transformers
  - mtl

ghc-options: -Wall -threaded

source-dirs:
  - src

executables:
  sensei:
    source-dirs: driver
    main: sensei.hs

  sensei-web:
    source-dirs: driver
    main: sensei-web.hs

  seito:
    source-dirs: driver
    main: seito.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec >= 2.9.0
      - hspec-contrib >= 0.5.2
      - temporary
      - QuickCheck
      - hspec-wai
      - mockery
    cpp-options: -DTEST
    build-tools: hspec-discover
