name: sensei
version: 0.6.2
synopsis: Automatically run Hspec tests on file modifications
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: hspec/sensei
category: Development

dependencies:
  - base >= 4.11 && < 5
  - process
  - fsnotify
  - time
  - wai
  - warp
  - http-types
  - stm
  - text
  - network
  - ansi-terminal
  - directory
  - http-client >= 0.5.0
  - bytestring
  - filepath
  - unix

ghc-options: -Wall

source-dirs:
  - src
  - doctest/ghci-wrapper/src/

executables:
  sensei:
    source-dirs: driver
    main: sensei.hs

  sensei-web:
    source-dirs: driver
    main: sensei-web.hs

  seito:
    source-dirs: driver
    main: seito.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec >= 2.9.0
      - hspec-wai
      - mockery
      - silently
    cpp-options: -DTEST
    build-tools: hspec-discover
