name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-12
        ghc:
          - '9.10'

    steps:
      - uses: actions/checkout@v3
      - uses: hspec/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
        id: setup-haskell

      - uses: actions/cache@v3
        with:
          path: ${{ runner.os == 'Windows' && 'C:/cabal/store/' || runner.os == 'macOS' && '~/.cabal/store/' || '~/.local/state/cabal/store/' }}
          key: ${{ runner.os }}-${{ steps.setup-haskell.outputs.ghc-version }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-${{ steps.setup-haskell.outputs.ghc-version }}-

      - shell: bash
        run: ghcup install cabal latest --set

      - shell: bash
        run: git config --global init.defaultBranch main

      - shell: bash
        run: cabal update

      - shell: bash
        run: cabal build all

      - shell: bash
        run: |
          for GHC in 9.4 9.6 9.8 9.10
          do
            ghcup install ghc $GHC --no-set
            SENSEI_GHC=ghc-$GHC $(cabal list-bin spec)
          done

  success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: false
        if: needs.build.result != 'success'

      - uses: actions/checkout@v3
      - name: Check for trailing whitespace
        run: '! git grep -I "\s\+$"'
