name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ghc:
          - '9.4'
          - '9.6'
          - '9.8'
          - '9.10'
        include:
          - os: macos-12
            ghc: system
    steps:
      - uses: actions/checkout@v4

      - uses: hspec/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
        id: setup-haskell

      - uses: actions/cache@v3
        with:
          path: ${{ runner.os == 'Windows' && 'C:/cabal/store/' || runner.os == 'macOS' && '~/.cabal/store/' || '~/.local/state/cabal/store/' }}
          key: ${{ runner.os }}-${{ steps.setup-haskell.outputs.ghc-version }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-${{ steps.setup-haskell.outputs.ghc-version }}-

      - shell: bash
        run: ghcup install cabal latest --set

      - shell: bash
        run: git config --global init.defaultBranch main

      - shell: bash
        run: cabal update

      - shell: bash
        run: cabal build all

      - shell: bash
        run: $(cabal list-bin spec) --times --print-slow
        env:
          HSPEC_OPTIONS: --color

      - run: vim/test/run.vim
        if: runner.os == 'Linux'

      - run: vim/test/assets/generate.sh
        if: ${{ runner.os == 'Linux' && matrix.ghc != '9.4' }}

      - run: git diff --exit-code

      - shell: bash
        run: |
          untracked=$(git ls-files --others --exclude-standard)
          if [ -n "$untracked" ]; then
            echo "Untracked files:"
            echo "$untracked"
            exit 1
          fi

  success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: false
        if: needs.build.result != 'success'

      - uses: actions/checkout@v4
      - name: Check for trailing whitespace
        run: "! git grep -nI '[[:blank:]]$' -- . ':!vim/test/assets'"
